config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  # マイページのルーティング
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  # トップページのルーティング
  #root to: 'home#top'


  #resources :users, only: [:index, :show, :edit, :update]
  resources :messages, :only => [:create,:destroy]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello#index' => 'hello#index'
  root 'hello#index'
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'


  # get 'tweets' => 'tweets#index'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id' => 'tweets#show',as: 'tweet'
  # patch 'tweets/:id'=> 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'
  # get 'tweets/:id/edit' => 'tweets#edit' , as:'edit_tweet'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]





  resources :users do
    resource :relationships, only: [:create, :destroy,:edit,:update]
    get :followings, on: :member
    get :followers, on: :member

    member do
      get :likes
    end

  end

  #resource :skills
  get 'skills' => 'skills#index'
  get 'skills/new' => 'skills#new'
  post 'skills' => 'skills#create'
  get 'skills/:id' => 'skills#show',as: 'skill'
  patch 'skills/:id'=> 'skills#update'
  put 'skills/:id'=> 'skills#update'
  delete 'skills/:id' => 'skills#destroy'
  get 'skills/:id/edit' => 'skills#edit' , as:'edit_skill'

  # devise_for :users, controllers: {
  # sessions: "users/sessions",
  #     registrations: "users/registrations"
  #   }

  resources :notifications, only: [:index,:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_many :notifications, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :room, optional: true
  belongs_to :message, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # フォローするユーザに結びついている
  belongs_to :following, class_name: "User"
  # フォローされるユーザに結びついている
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  has_many :notifications, dependent: :destroy
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user


  # with_options presence: true do
  #   validates :language_name
  #   validates :image
  #   validates :evaluation
  # end

  mount_uploader :image, ImageUploader


end

app/models/tag.rb
class Tag < ApplicationRecord

  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet.rb
class Tweet < ApplicationRecord

mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  #追記したぞ
  has_many :skills, dependent: :destroy


  # フォローする側から中間テーブルへのアソシエーション
  has_many :relationships, foreign_key: :following_id
  # フォローする側からフォローされたユーザを取得する
  has_many :followings, through: :relationships, source: :follower

  # フォローされる側から中間テーブルへのアソシエーション
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  # フォローされる側からフォローしているユーザを取得する
  has_many :followers, through: :reverse_of_relationships, source: :following



  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy


  mount_uploader :image, ImageUploader

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  # あるユーザが引数で渡されたuserにフォローされているか調べるメソッド
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end


  def update_without_current_password(params, *options)
  params.delete(:current_password)
  if params[:password].blank? && params[:password_confirmation].blank?
    params.delete(:password)
    params.delete(:password_confirmation)
  end
  result = update_attributes(params, *options)
  clean_up_passwords
  result
  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def link
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<html>
  <main>
  <!--<header class="page-header wrapper">
    <%= link_to tweets_path do%>
      <h1 class="after_login">PORTFOLIO GARDEN</h1>
    <% end %>

    <nav>
      <ul class="main-nav">
        <% if user_signed_in? %>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "POST", new_tweet_path %></li>
        <li class="header-icon">
        <%= link_to user_path(current_user.id) do %>
          <% if current_user.image?  %>
              <%= image_tag current_user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if current_user.image? %>
          <% else %>
            <%= image_tag "default.png", size: '50x50' %>
          <% end %>
        <% end %>
        </li>
      </ul>
      <% end %>
    </nav>
  </header>

    <%= link_to "ログイン", tweets_path %>
    <%= link_to "新規登録", new_user_registration_path %>-->


    <section class="title-section">
      <div class="title-part">
        <div class="title-text-all">
          <p class="title-text">PORTFOLIO GARDEN<p>
          <p class="hello-text">駆け出しエンジニアが<br>
          作品を通してつながる場所。</p>
        </div>
        <div class="title-image">
          <%= image_tag "bench.jpeg", alt: "post-image", id: :img_prev, size: "700x700",class:"hello-img"%>
        </div>
      </div>
    </section>

    <section class="worry-section">
    <div class="worry-part">
      <div>
        <%= image_tag "worry.jpeg", alt: "post-image", id: :img_prev, size: "800x800",class:"hello-img"%>
      </div>
      <div class="worry-text element">
        <span class="japanese-title">1人で悩まないで</span>
        <p class="hello-text">プログラミング学習はエラーで挫折してしまう<br>
        そんな人のために PORTFOLIO GARDEN は作られました。<br>
        サイトを通して出会った仲間と一緒にエンジニアへの<br>
        一歩を踏み出しましょう。</p>
      </div>
    </section>

    <section>

      <div class="plant-part">
        <div class="plant-text element">
          <span class="japanese-title">みんなで育てる</span>
          <p class="hello-text">
          あなたは同世代や先輩たちの投稿を投稿を観ることが出来ます。<br>
          あなたの投稿が同世代や後輩に勇気を与えます。<br>
          一緒にエンジニアが駆け出すためのプラットフォームを<br>
          作りませんか。
          </p>
        </div>
        <div>
          <%= image_tag "plant.jpeg", alt: "post-image", id: :img_prev, size: "800x800",class:"hello-img"%>
        </div>
      </div>
    </section>

  </main>
</html>

app/views/hello/link.html.erb
<h1>PORTFOLIO GARDEN</h1>
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', :controller => "tweets", :action => "index" %>