config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  # マイページのルーティング
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  # トップページのルーティング
  #root to: 'home#top'


  #resources :users, only: [:index, :show, :edit, :update]
  resources :messages, :only => [:create,:destroy]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello#index' => 'hello#index'
  root 'hello#index'
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'


  # get 'tweets' => 'tweets#index'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id' => 'tweets#show',as: 'tweet'
  # patch 'tweets/:id'=> 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'
  # get 'tweets/:id/edit' => 'tweets#edit' , as:'edit_tweet'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]





  resources :users do
    resource :relationships, only: [:create, :destroy,:edit,:update]
    get :followings, on: :member
    get :followers, on: :member

    member do
      get :likes
    end

  end

  #resource :skills
  get 'skills' => 'skills#index'
  get 'skills/new' => 'skills#new'
  post 'skills' => 'skills#create'
  get 'skills/:id' => 'skills#show',as: 'skill'
  patch 'skills/:id'=> 'skills#update'
  put 'skills/:id'=> 'skills#update'
  delete 'skills/:id' => 'skills#destroy'
  get 'skills/:id/edit' => 'skills#edit' , as:'edit_skill'

  # devise_for :users, controllers: {
  # sessions: "users/sessions",
  #     registrations: "users/registrations"
  #   }

  resources :notifications, only: [:index,:update]

end

app/models/tweet.rb
class Tweet < ApplicationRecord

mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    # if params[:tag_id].present?
    #     @tweets = Tag.find(params[:tag_id]).tweets.page(params[:page]).per(3)
    # elsif params[:search] == nil
    #     @tweets= Tweet.all.page(params[:page]).per(3)
    # elsif params[:search] == ''
    #     @tweets= Tweet.all.page(params[:page]).per(3)
    # else
    #     #部分検索
    #     @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(3)
    # end
    # @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets.page(params[:page]).per(3) : Tweet.all.page(params[:page]).per(3)



    # @tweets= Tweet.all.page(params[:page]).per(3)
    # @tags = Tag.all.page(params[:page]).per(3)
    # @tweets = @tweets.where("body LIKE ? ",'%' + params[:search] + '%') if params[:search].present?
    # もしタグ検索したら、tweet_idsにタグを持ったidをまとめてそのidで検索
    # if params[:tag_ids].present?
      # tweet_ids = []
      # params[:tag_ids].each do |key, value|
        # if value == "1"
          # Tag.find_by(name: key).tweets.each do |p|
            # tweet_ids << p.id
          # end
        # end
      # end
      # tweet_ids = tweet_ids.uniq
      # キーワードとタグのAND検索
      # @tweets = @tweets.where(id: tweet_ids).page(params[:page]).per(3) if tweet_ids.present?
    # end

    if params[:search].blank? && params[:tag_id].blank?
      @tweets= Tweet.all.order(created_at: :desc).page(params[:page]).per(6)
    elsif params[:search].present? && params[:tag_id].blank?
      @tweets= Tweet.order(created_at: :desc).where("body LIKE ? OR title LIKE ? OR language LIKE ?",'%' + params[:search] + '%','%' + params[:search] + '%','%' + params[:search] + '%').page(params[:page]).per(6)
    elsif params[:search].blank? && params[:tag_id].present?
      @tweets = Tag.find(params[:tag_id]).tweets.order(created_at: :desc).page(params[:page]).per(6)
    else
      @tweets = Tag.find(params[:tag_id]).tweets.order(created_at: :desc).where("body LIKE ? OR title LIKE ? OR language LIKE ?",'%' + params[:search] + '%','%' + params[:search] + '%','%' + params[:search] + '%').page(params[:page]).per(6)
    end


  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action =>"index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
        @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to user_path(current_user.id)
  end

  private
    def tweet_params
      params.require(:tweet).permit(:body, :image, :title, :language,:tweet_url, tag_ids: [])
    end
    # def article_params
    #   params.require(:article).permit(:body, tag_ids: [])
    # end
  end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<%# javascript_pack_tag 'posts' %>
  <html>
    <!--<header class="page-header wrapper">
      <%= link_to tweets_path do%>
        <h1 class="after_login">PORTFOLIO GARDEN</h1>
      <% end %>
      <nav>
        <ul class="main-nav">
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% if user_signed_in? %>
          <li><%= link_to "POST", new_tweet_path %></li>
          <li class="header-icon">
          <%= link_to user_path(current_user.id) do %>
            <% if current_user.image?  %>
                <%= image_tag current_user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if current_user.image? %>
            <% else %>
              <%= image_tag "default.png", size: '50x50' %>
            <% end %>
          <% end %>
          </li>
        </ul>
        <% end %>
      </nav>
    </header>-->
    <main>
      <%= form_for @tweet do |f| %>
      <div class="field">
        <%= f.label :title %>
        <br>
        <%= f.text_field :title, :size => 30,class:"mb-3 form-size-2" %>
      </div>

      <%= f.label :language %>
      <div class='form-group list--3'>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
              <div class='form-check'>
                  <%= tag.label class: 'form-check-label' do %>
                      <%= tag.check_box class: 'form-check-input' %>
                      <%= tag.text %>
                  <% end %>
              </div>
          <% end %>
      </div>
      <!--<div class="field">
        <%= f.label :body %>
        <%= f.text_field :body, :size => 140 %>
      </div>-->
      <div class="field">
        <%= f.label :concept %>
        <br>
        <%= f.text_area :body, size: "70x15", maxlength: "1000", placeholder: "紹介文を書く", :class => 'form-size-2' %>
      </div>

      <!--<div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>-->

      <div>
        <%= f.label :thumbnail, class: "label" %>
        <br>
        <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png', id: "image-select-btn" %>
      </div>
      <div class="post-image-prev">
        <% if @tweet.image? %>
          <%= image_tag @tweet.image.url, alt: "post-image", id: "img_prev", size: "320x180" %>
        <% else %>
          <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "320x180" %>
        <% end %>
      </div>

      <br>

      <%= f.label :url %>

      <div class="mb-3">
        <%= f.text_field :tweet_url, :size => 30, class:'form-size-2' %>
      </div>

      <div class="field">
        <%= f.label :graduates %>
        <br>
        <%= f.select :language,
        [["23卒", "23卒"],
        ["24卒", "24卒"],
        ["25卒", "25卒"]], include_blank: "選択して下さい"%>
      </div>
      <%= f.submit "編集する",class:"mt-3 btn btn-border" %>
      <% end %>
    </main>
  </html>

app/views/tweets/index.html.erb
<html>

  <!--<header class="page-header wrapper">
    <%= link_to tweets_path do%>
      <h1 class="after_login">PORTFOLIO GARDEN</h1>
    <% end %>

    <nav>
      <ul class="main-nav">
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% if user_signed_in? %>
        <li><%= link_to "POST", new_tweet_path %></li>
        <li class="header-icon">
        <%= link_to user_path(current_user.id) do %>
          <% if current_user.image?  %>
              <%= image_tag current_user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if current_user.image? %>
          <% else %>
            <%= image_tag "default.png", size: '50x50' %>
          <% end %>
        <% end %>
        </li>
      </ul>
      <% end %>
    </nav>
  </header>-->




  <!--
  <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
  <% end %>

  <%= form_tag tweets_path, method: :get, class: 'boards__searchForm' do %>
        <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
            {
              prompt: 'タグで絞り込み検索',
              #onchange: 'submit(this.form);'
            }
        %>
        <%= submit_tag '検索する' %>
  <% end %>
  -->

<main>
<br>
    <ul class="search-down">
        <%= form_tag({controller:"tweets",action:"index"},method: :get)do %>
          <%= text_field_tag :search ,{},class:"form-size-1"%>
            <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
            {
              prompt: 'タグで絞り込み',
            }%>
        <%= submit_tag '検索' , class: "btn btn-blue" %>
      <% end %>
    <br>
    <%= page_entries_info @tweets %>
    </ul>
    <hr width="98%">
    <div class="warapper grid">
      <% @tweets.each do |t| %>
        <div class="tweet">
          <% if user_signed_in? %>
            <%= link_to user_path(t.user.id) , class: 'anti-line' do %>
              <% if t.user.image?  %>
                <span class="user-icon">
                  <%= image_tag t.user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if t.user.image? %>
                </span>
              <% else %>
                <span class="user-icon">
                  <%= image_tag "default.png", size: '50x50',class: "mb-3" %>
                </span>
              <% end %>
              <span class="name-font-tweet">
              <%= t.user.name %>
              </span>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path ,class: 'anti-line' do%>
              <% if t.user.image?  %>
                <span class="user-icon">
                  <%= image_tag t.user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if t.user.image? %>
                </span>
              <% else %>
                <span class="user-icon">
                  <%= image_tag "default.png", size: '50x50',class: "mb-3"  %>
                </span>
              <% end %>
              <span class="name-font-tweet">
              <%= t.user.name %>
              </span>
            <% end %>
          <% end %>
          <br>
          <%= link_to tweet_path(t.id) do%>

            <% if t.image?  %>
              <span class="tweet-image-line">
                <%= image_tag t.image_url, size: "320x180" , class: 'image-down'if t.image? %>
              </span>
            <% else %>
              <span class="tweet-image-line">
                <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "320x180"%>
              </span>
            <% end %>
          <% end %>
          <br>
          <% t.tags.each do |tag| %>
              <span class="tag-element-border"><%= tag.name %></span>
          <% end %>
          <%= t.language %>
          <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                  <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete , class: 'anti-line' do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% else %>
                  <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post , class: 'anti-line' do %>
                      <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% end %>
          <% else %>
            <%= link_to new_user_session_path, class: 'anti-line' do%>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
          <br>
          <%= t.created_at %>
          <%= link_to "詳細",tweet_path(t.id) , class: 'anti-line'%>
        </div>
      <% end %>
    </div>
    <hr width="98%">
</main>
<br>

  <section class="paginate-2">
      <%= paginate @tweets, theme: 'bootstrap-5' %>
  </section>
</html>

app/views/tweets/new.html.erb
<%# javascript_pack_tag 'posts' %>
  <html>
      <!--<header class="page-header wrapper">
        <%= link_to tweets_path do%>
          <h1 class="after_login">PORTFOLIO GARDEN</h1>
        <% end %>
        <nav>
          <ul class="main-nav">
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% if user_signed_in? %>
            <li><%= link_to "POST", new_tweet_path %></li>
            <li class="header-icon">
            <%= link_to user_path(current_user.id) do %>
              <% if current_user.image?  %>
                  <%= image_tag current_user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if current_user.image? %>
              <% else %>
                <%= image_tag "default.png", size: '50x50' %>
              <% end %>
            <% end %>
            </li>
          </ul>
          <% end %>
        </nav>
      </header>-->
    <main>
      <h3>POST</h3>
      <%= form_for @tweet do |f| %>
      <%= f.label :title %>


      <div>
        <%= f.text_field :title, :size => 30, class:'form-size-2' %>
      </div>
      <br>
      <%= f.label :language %>
      <div class='form-group list--3'>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
              <div class='form-check'>
                  <%= tag.label class: 'form-check-label' do %>
                      <%= tag.check_box class: 'form-check-input' %>
                      <%= tag.text %>
                  <% end %>
              </div>
          <% end %>
      </div>
      <br>

      <div class="row">
        <div class="col-md-4">
          <div class="field">
            <%= f.label :concept %>
            <br>
            <%= f.text_area :body, size: "70x15", maxlength: "1000", placeholder: "紹介文を書く", class:'form-size-2' %>
          </div>
        </div>
      </div>
      <!--<div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>-->
      <br>
      <div class="form-group mb-3">
        <%= f.label :thumbnail, class: "label" %>
        <br>
        <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png', id: "image-select-btn" %>
      </div>
      <div class="post-image-prev">
        <% if @tweet.image? %>
          <%= image_tag @tweet.image.url, alt: "post-image", id: "img_prev", size: "320x180"%>
        <% else %>
          <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "320x180" %>
        <% end %>
      </div>
      <br>

      <%= f.label :url %>
      <div class="mb-3">
          <div class="col-md-4">
              <%= f.text_field :tweet_url, :size => 30, class:'form-size-2' %>
          </div>
      </div>

      <div class="field">
        <%= f.label :graduates %>
        <br>
        <%= f.select :language,
        [["23卒", "23卒"],
        ["24卒", "24卒"],
        ["25卒", "25卒"]], include_blank: "選択して下さい" %>
      </div>
      <br>
      <input type="button" onclick="submit();" value="post" class="btn btn-border mb-3"/>
      <% end %>
      <%= link_to "PORTFOLIO", tweets_path , class: 'anti-line'%>
    </main>
  </html>

app/views/tweets/show.html.erb
  <html>
    <main>
      </p>
      <h2>PORTFOLIO詳細</h2>
      <div class="tweet">
        <p>
          <% if user_signed_in? %>
            <%= link_to user_path(@tweet.user.id) ,class: 'user-icon anti-line' do %>
              <% if @tweet.user.image? %>
                <%= image_tag @tweet.user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if @tweet.user.image? %>
              <% else %>
                <%= image_tag "default.png", size: '50x50' ,class: "mb-3" %>
              <% end %>
              <span class="name-font-tweet">
                <%= @tweet.user.name %>
              </span>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path,class: 'user-icon anti-line' do%>
              <% if @tweet.user.image? %>
                <%= image_tag @tweet.user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if @tweet.user.image? %>
              <% else %>
                <%= image_tag "default.png", size: '50x50' ,class: "mb-3"%>
              <% end %>
              <span class="name-font-tweet">
                <%= @tweet.user.name %>
              </span>
            <% end %>
          <% end %>
        </p>
        <h3><%= @tweet.title %></h3>
        <% if @tweet.image?  %>
          <span class="tweet-image-line">
          <%= image_tag @tweet.image_url, size: "320x180", class: 'image-down' if @tweet.image? %>
          </span>
        <% else %>
          <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "320x180"%>
        <% end %>
        <br>
        <% @tweet.tags.each do |tag| %>
            <span class="tag-element-border"><%= tag.name %></span>
        <% end %>
        <%= @tweet.language %>
        <% if user_signed_in? %>
            <% if current_user.already_liked?(@tweet) %>
                <%= link_to tweet_like_path(@tweet), method: :delete ,class: 'anti-line' do %>
                  <i class="fas fa-heart"></i><%= @tweet.likes.count %>
                <% end %>
            <% else %>
                <%= link_to tweet_likes_path(@tweet), method: :post ,class: 'anti-line' do %>
                  <i class="far fa-heart"></i><%= @tweet.likes.count %>
                <% end %>
            <% end %>
        <% else %>
            <%= link_to new_user_session_path ,class: 'anti-line' do %>
              <i class="far fa-heart"></i><%= @tweet.likes.count %>
            <% end %>
        <% end %>
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <%= link_to "編集する", edit_tweet_path(@tweet.id) ,class: 'anti-line' %>
          <%= link_to "削除する", tweet_path(@tweet.id), method: :delete ,class: 'anti-line' %>
        <% end %>
        <p><%= @tweet.created_at %></p>
        <p class="anti-margin-bottom">concept</p>
        <div class="body-design mb-3">
          <p><%=safe_join(@tweet.body.split("\n"),tag(:br))%></p>
        </div>
        <p class="anti-margin-bottom">URL</p>
        <div class="url-box">
          <%= text_url_to_link((h(@tweet.tweet_url).html_safe)).html_safe %>
        </div>
        <br>



        <%# @tweet.body %>
        <div class="Subheading">
          <p class="user-show-h2">いいねしたユーザー</p>
          <hr width="50%">
        </div>
        <% @tweet.liked_users.each do |user| %>
          <% if user_signed_in? %>
            <%= link_to user_path(user.id) ,class: 'anti-line user-icon' do %>
              <% if user.image? %>
                <%= image_tag user.image_url, size: '25x25', fallback: "no_image.png", class: "mb-3 profile-img" if user.image? %>
              <% else %>
                <%= image_tag "default.png", size: '25x25', class: "mb-3" %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path ,class: 'anti-line user-icon ' do%>
              <% if user.image? %>
                <%= image_tag user.image_url, size: '25x25', fallback: "no_image.png", class: "mb-3 profile-img" if user.image? %>
              <% else %>
                <%= image_tag "default.png", size: '25x25', class: "mb-3" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <br>

      <div class="comment-wrapper">
      <div class="Subheading">
          <p class="user-show-h2">コメント一覧</p>
          <hr width="50%">
      </div>
      <br>
      <% @comments.each do |c| %>
        <div>
            <% if user_signed_in? %>
              <%= link_to user_path(c.user.id) ,class: 'anti-line user-icon' do %>
                  <% if c.user.image? %>
                    <%= image_tag c.user.image_url, size: '25x25', fallback: "no_image.png", class: "mb-3 profile-img" if c.user.image? %>
                  <% else %>
                    <%= image_tag "default.png", size: '25x25' %>
                  <% end %>
                  <span class="name-font-tweet">
                  <%= c.user.name unless c.user.blank?%>
                  </span>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path ,class: 'anti-line user-icon' do%>
                  <% if c.user.image? %>
                    <%= image_tag c.user.image_url, size: '25x25', fallback: "no_image.png", class: "mb-3 profile-img" if c.user.image? %>
                  <% else %>
                    <%= image_tag "default.png", size: '25x25' %>
                  <% end %>
                  <span class="name-font-tweet">
                  <%= c.user.name unless c.user.blank?%>
                  </span>
              <% end %>
            <% end %>

          <%# c.user.email unless c.user.blank? %>
          <br>
          <%= c.content %>
          <% if user_signed_in? && current_user.id == c.user_id %>
            <%= link_to  comment_path(c.id), method: :delete ,class: 'anti-line' do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
        <br>
      <% end %>
      <% if user_signed_in? %>
        <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
          <%= f.text_area :content ,class:"form-size-1" %>
          <br>
          <%= button_tag type: "submit" ,class:"btn btn-border" do %>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        <% end %>

      <% else %>
        <br>
        <div>
          <%= link_to new_user_session_path ,class: 'btn btn-border' do%>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        </div>
      <% end %>
      </div>


      <!--<p><%= @tweet.user.email %></p>-->
      <%= link_to "PORTFOLIOに一覧に戻る",tweets_path ,class: 'anti-line' %>
    </main>
  </html>