config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  # マイページのルーティング
  get 'users/:id/profile', to: 'users#show', as: 'user_profile'
  # トップページのルーティング
  #root to: 'home#top'


  #resources :users, only: [:index, :show, :edit, :update]
  resources :messages, :only => [:create,:destroy]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello#index' => 'hello#index'
  root 'hello#index'
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'


  # get 'tweets' => 'tweets#index'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id' => 'tweets#show',as: 'tweet'
  # patch 'tweets/:id'=> 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'
  # get 'tweets/:id/edit' => 'tweets#edit' , as:'edit_tweet'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]





  resources :users do
    resource :relationships, only: [:create, :destroy,:edit,:update]
    get :followings, on: :member
    get :followers, on: :member

    member do
      get :likes
    end

  end

  #resource :skills
  get 'skills' => 'skills#index'
  get 'skills/new' => 'skills#new'
  post 'skills' => 'skills#create'
  get 'skills/:id' => 'skills#show',as: 'skill'
  patch 'skills/:id'=> 'skills#update'
  put 'skills/:id'=> 'skills#update'
  delete 'skills/:id' => 'skills#destroy'
  get 'skills/:id/edit' => 'skills#edit' , as:'edit_skill'

  # devise_for :users, controllers: {
  # sessions: "users/sessions",
  #     registrations: "users/registrations"
  #   }

  resources :notifications, only: [:index,:update]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  #追記したぞ
  has_many :skills, dependent: :destroy


  # フォローする側から中間テーブルへのアソシエーション
  has_many :relationships, foreign_key: :following_id
  # フォローする側からフォローされたユーザを取得する
  has_many :followings, through: :relationships, source: :follower

  # フォローされる側から中間テーブルへのアソシエーション
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  # フォローされる側からフォローしているユーザを取得する
  has_many :followers, through: :reverse_of_relationships, source: :following



  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy


  mount_uploader :image, ImageUploader

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  # あるユーザが引数で渡されたuserにフォローされているか調べるメソッド
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end


  def update_without_current_password(params, *options)
  params.delete(:current_password)
  if params[:password].blank? && params[:password_confirmation].blank?
    params.delete(:password)
    params.delete(:password_confirmation)
  end
  result = update_attributes(params, *options)
  clean_up_passwords
  result
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end



  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # def after_update_path_for(resource)
  #   # 自分で設定した「マイページ」へのパス
  #   user_profile_path(current_user)
  # end



  def after_update_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
  # サインアップ時にnameのストロングパラメータを追加
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  # アカウント編集の時にnameとprofileのストロングパラメータを追加
  devise_parameter_sanitizer.permit(:account_updare, keys: [:name, :email, :profile, :image])

  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  # def new
  #   render template: "skills/new"
  # end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @skill = Skill.new
    @skills=Skill.all.order("id")
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def likes
    @skill = Skill.new
    @skills=Skill.all.order(created_at: :asc)
    @user = User.find(params[:id])
    likes = Like.where(user_id: @user.id).pluck(:tweet_id)
    @like_tweets = Tweet.find(likes)
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :profile, :image)
    end

    def set_user
      @user = User.find([:id])
    end



  # def user_params
    # params.fetch(:user, {}).permit(:username)
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
  <html>

    <main>
      <h2>プロフィール編集</h2>
      <%= form_with model: @user do |form| %>
        <!--<div class="field">
          <%= form.label :image %><br/>
          <%= form.file_field :image %>
        </div>-->


        <div class="form-group mb-3">
          <%= form.label :image %><br/>
          <%= form.file_field :image, accept: 'image/jpeg, image/gif, image/png', id: "image-select-btn" %>
        </div>
        <div class="post-image-prev">
          <span class="profile-icon">
            <% if @user.image? %>
              <%= image_tag @user.image.url, alt: "post-image", id: "img_prev", size: "100x100" %>
            <% else %>
              <%= image_tag "default.png", size: '100x100' %>
            <% end %>
          </span>
        </div>

        <br>




        <!--アカウント編集時に名前を入力できるようにフォームを追加-->
        <div class="field">
          <%= form.label :name %><br />
          <%# form.text_field :name, autofocus: true %>
        </div>

        <div>
          <%= form.text_field :name, autofocus: true, class:'form-size-1 mb-3' %>
        </div>



        <div class="field">
          <%= form.label :email %><br />
          <%# form.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>

        <div>
          <%= form.email_field :email, autofocus: true, autocomplete: "email",class:'form-size-1 mb-3'%>
        </div>
        <!--アカウント編集時にプロフィールを入力できるようにフォームを追加-->

        <div>
          <%= form.label :profile %>
          <br>
          <%= form.text_area :profile, autofocus: true, maxlength: "200", placeholder: "紹介文を書く", class:'form-size-3 mb-3' %>
        </div>

        <div class="mb-3"><%= form.submit "保存" %></div>
      <% end %>
      <%= link_to "戻る", :back %>
    </ main>
  </html>

app/views/users/followers.html.erb
  <html>
    <!--<header class="page-header wrapper">
      <%= link_to tweets_path do%>
        <h1 class="after_login">PORTFOLIO GARDEN</h1>
      <% end %>
      <nav>
        <ul class="main-nav">
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% if user_signed_in? %>
          <li><%= link_to "POST", new_tweet_path %></li>
          <li class="header-icon">
          <%= link_to user_path(current_user.id) do %>
            <% if current_user.image?  %>
                <%= image_tag current_user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if current_user.image? %>
            <% else %>
              <%= image_tag "default.png", size: '50x50' %>
            <% end %>
          <% end %>
          </li>
        </ul>
        <% end %>
      </nav>
    </header>-->
    <main>

          <div class="tab-follow">
            <%= link_to followings_user_path,class:'anti-line'  do %>
              <span class="follow-font tab-hover en-character">FOLLOWING</span>
            <%end%>
            <div class="tab-line"></div>
            <span class="follow-font en-character">FOLLOWERS</span>
          </div>
          <table class="table follow-table">
            <thead>
              <tr>
                <th>Name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= link_to user_path(user),class:'anti-line' do %>
                      <span class="user-icon">
                      <% if user.image? %>
                        <%= image_tag user.image_url, size: '50x50', class: "profile-img" if user.image? %>
                      <% else %>
                        <%= image_tag "default.png", size: '50x50' %>
                      <% end %>
                      </span>
                      <span class="name-font-tweet">
                      <%= user.name %>
                      </span>
                    <% end %>
                  </td>
                  <td>
                    <% if user != current_user %>
                      <% if user.is_followed_by?(current_user) %>
                        <%=link_to user_relationships_path(user), method: :delete do %>
                          <button type="button" class="btn btn-border mt-2">フォロー解除</button>
                        <% end %>
                      <% else %>
                        <%=link_to user_relationships_path(user), method: :post do %>
                          <button type="button" class="btn btn-green mt-2">フォロー</button>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
      <%= link_to "ユーザーページに戻る",   user_profile_path,class:'anti-line' %>
    </main>
  </html>

app/views/users/followings.html.erb
  <html>
    <!--<header class="page-header wrapper">
      <%= link_to tweets_path do%>
        <h1 class="after_login">PORTFOLIO GARDEN</h1>
      <% end %>
      <nav>
        <ul class="main-nav">
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% if user_signed_in? %>
          <li><%= link_to "POST", new_tweet_path %></li>
          <li class="header-icon">
          <%= link_to user_path(current_user.id) do %>
            <% if current_user.image?  %>
                <%= image_tag current_user.image_url, size: '50x50', fallback: "no_image.png", class: "mb-3 profile-img" if current_user.image? %>
            <% else %>
              <%= image_tag "default.png", size: '50x50' %>
            <% end %>
          <% end %>
          </li>
        </ul>
        <% end %>
      </nav>
    </header>-->
    <main>
          <div class="tab-follow">

            <span class="follow-font en-character">FOLLOWING</span>
            <div class="tab-line"></div>
            <%= link_to followers_user_path,class:'anti-line' do %>
            <span class="follow-font en-character tab-hover">FOLLOWERS</span>
            <% end %>
          </div>
          <table class="table follow-table">
            <thead>
              <tr>
                <th>Name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= link_to user_path(user) ,class:'anti-line' do %>
                    <span class="user-icon">
                    <% if user.image? %>
                      <%= image_tag user.image_url, size: '50x50', class: "profile-img" if user.image? %>
                    <% else %>
                      <%= image_tag "default.png", size: '50x50' %>
                    <% end %>
                    </span>
                    <span class="name-font-tweet">
                      <%= user.name %>
                    </span>
                    <% end %>
                  </td>
                  <td>
                    <% if user != current_user %>
                      <% if user.is_followed_by?(current_user) %>
                        <%=link_to user_relationships_path(user), method: :delete do %>
                          <button type="button" class="btn btn-border mt-2">フォロー解除</button>
                        <% end %>
                      <% else %>
                        <%=link_to user_relationships_path(user), method: :post do %>
                          <button type="button" class="btn btn-green mt-2">フォロー</button>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
      <%= link_to "ユーザーページに戻る",   user_profile_path,class:'anti-line' %>
    </main>
  </html>

app/views/users/index.html.erb
<% if user_signed_in? %>
<h2>Hello <%= current_user.email %></h2>
  <% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.email %>さん</a></p>
  <hr>
  <% end %>

  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>

<% else %>
  <%= link_to "ユーザーを登録する", new_user_registration_path %>
  <br>
  <%= link_to "ログインする", new_user_session_path %>
<% end %>

<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<html>


<main>
  <!--<p>
  <% if @user != current_user %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>
  </p>-->
  <div class="user-page-flex1">
    <section>
      <p>
      <h3 class="fw-light">
        <div class="d-flex">
          <span class="profile-icon">
            <% if @user.image?  %>
                <%= image_tag @user.image_url, size: '100x100', class: "mb-3 profile-img" if @user.image? %>
            <% else %>
              <%= image_tag "default.png", size: '100x100', class: "mb-3" %>
            <% end %>
          </span>
        </div>
        <%= @user.name %>
        <% if @user == current_user %>
          <%=link_to  notifications_path do%>
            <i class="fas fa-bell"></i>
          <% end %>
        <% end %>
      </h3>
      </p>
      <!--<p>メールアドレス : <%= @user.email %></p>-->
      <section class="margin-bottom-1rem">
      <div class="field">
          <div>
            <div>
              <% if @user == current_user %>
                <p class="lead text-muted"><%= current_user.email %></p>
              <% else %>
                <% if @user.is_followed_by?(current_user) %>
                  <%=link_to user_relationships_path(@user), method: :delete do %>
                    <button type="button" class="btn  btn-border">フォロー解除</button>
                  <% end %>
                <% else %>
                  <%=link_to user_relationships_path(@user), method: :post do %>
                    <button type="button" class="btn  btn-green">フォロー</button>
                  <% end %>
                <% end %>
              <% end %>
              <p class="text-small"><%= link_to @user.followings.count, followings_user_path(@user) , class: 'anti-line'%> フォロー <%= link_to @user.followers.count, followers_user_path(@user) , class: 'anti-line' %> フォロワー</p>
            </div>
          </div>
      </div>
      <div class="box11">
        <%= @user.profile %>
      </div>
      <% if current_user.id == @user.id %>
      <%= button_to "プロフィール編集", edit_user_path(current_user) , method: :get, class: 'anti-line btn btn-border' %>
      <% else %>
        <% if @isRoom == true %>
          <span><a href="/rooms/<%= @roomId %>">チャットへ</a></span>
        <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class:"btn btn-border mb-3" %>
        <% end %>
      <% end %>
      <% end %>
      </section>



        <div class="Subheading">
          <div class="user-show-h2">ユーザースキル</div>
          <hr width="100%">
        </div>
        <div class="scroll">
          <table class="SkillTable">
            <thead>
              <tr>
                <th>言語&nbsp;</th>
                <th>&nbsp;画像</th>
                <th>rank</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @user.skills.each do |s| %>
                <tr>
                  <td>
                    <%= s.language_name %></td>
                  <td>
                    <%= image_tag s.image_url, size: '50x50' if s.image? %>
                  <td>
                    <!-- <%= s.evaluation %> -->
                    <div class="relative-post-evaluation">
                      <span id="star-rate-<%= s.id %>"></span>
                      <script>
                        $('#star-rate-<%= s.id %>').empty();
                        $('#star-rate-<%= s.id %>').raty({
                          size: 36,
                          starOff: "<%= asset_path('star-off.png') %>",
                          starOn: "<%= asset_path('star-on.png') %>",
                          starHalf: "<%= asset_path('star-half.png') %>",
                          half: true,
                          readOnly: true,
                          score: <%= s.evaluation %>
                        });
                      </script>
                    </div>
                  </td>
                  <td>
                    <% if user_signed_in? && current_user.id == s.user_id %>
                      <%= link_to "編集する", edit_skill_path(s.id), remote: true , class: 'anti-line'%>
                      <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>





                    <% end %>
                  </td>
                  <td>
                    <% if user_signed_in? && current_user.id == s.user_id %>
                      <%= link_to  skill_path(s.id), method: :delete , class: 'anti-line icon-effect-hidden' do%>
                        <i class="fas fa-trash-alt"></i>

                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
          </table>
        </div>











        <!--<% if current_user.id == @user.id %>
          <%= link_to "スキル編集", skills_new_path(current_user) %>
        <% end %>-->

        <!-- Button trigger modal -->
        <% if current_user.id == @user.id %>
          <button data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-border mt-3">
            Skill add
          </button>
        <% end %>

        <!-- Modal -->
        <%= form_for @skill do |f| %>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Skill add</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="mb-3">
                  <%= f.label :language, class: "label" %>
                  <%= f.text_field :language_name,class:"form-size-1" %>
                </div>
                <div class="form-group mb-3">
                  <%= f.label :image, class: "label" %>
                  <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png', id: "image-select-btn" %>
                </div>
                <div class="post-image-prev">
                  <% if @skill.image? %>
                    <%= image_tag @skill.image.url, alt: "post-image", id: "img_prev", size: "50" %>
                  <% else %>
                    <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "50" %>
                  <% end %>
                </div>
                <%= f.label :evaluation, "星評価：" %>
                <div class="field" id="star">
                  <%= f.hidden_field :evaluation, id: :review_star %>
                    <script>
                      $('#star').empty();
                      $('#star').raty({
                        size     : 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        scoreName: 'skill[evaluation]',
                        half: true,
                      });
                    </script>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-border" data-bs-dismiss="modal">Close</button>
                <%= f.submit "登録", class:"btn btn-blue2"%>
              </div>
            </div>
          </div>
        </div>
        <% end %>
    </section>
    <section class="user-bench">
      <%= image_tag "bench.jpeg", alt: "post-image", id: :img_prev, size: "500x500",class:"hello-img"%>
    </section>
  </div>

    <br>

    <div class="Subheading2">
      <div class="user-tab">
        <div class="user-show-h2">投稿</div>
        <span class="tab-line"></span>
        <%= link_to likes_user_path(@user) , class: 'anti-line' do%>
        <div class="user-show-h2 tab-hover">いいね</div>
        <% end %>
      </div>
      <hr width="95%">
    </div>
    <div class="warapper grid-user">
      <% if @user.tweets.count == 0 %>
        <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "320x180"%>
      <% end %>
      <% @user.tweets.each do |t| %>
      <div class="tweet">
        <p>
        <%= link_to tweet_path(t.id) do%>
          <% if t.image?  %>
            <span class="tweet-image-line">

            <%= image_tag t.image_url, size: "320x180", class: 'image-down' if t.image? %>
            </span>
          <% else %>
            <span class="tweet-image-line">
              <%= image_tag "post-default.png", alt: "post-image", id: :img_prev, size: "320x180"%>
            </span>
          <% end %>
        <% end %>
        <br>
        <% t.tags.each do |tag| %>
          <span class="tag-element-border"><%= tag.name %></span>
        <% end %>
        <%= t.language %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete , class: 'anti-line' do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post , class: 'anti-line' do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        <br>
        <!--<%= t.body %>-->
        <%= t.created_at %>
        <%= link_to "詳細",tweet_path(t.id) , class: 'anti-line'%>
        <br>
        <!--<% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "編集する", edit_tweet_path(t.id) %>
        <%= link_to "削除する", tweet_path(t.id), method: :delete %>
        <% end %>-->
        </p>
      </div>
      <% end %>
    </div>

    <%= link_to "PORTFOLIO一覧", tweets_path , class: 'anti-line'%>
</main>
</html>

app/views/users/update.html.erb
<h1>PORTFOLIO GARDEN</h1>